name: mauritius_emergency_services
description: "A new Flutter project."
publish_to: 'none'
version: 1.5.0

environment:
  sdk: ^3.6.0

dependencies:

  flutter:
    sdk: flutter

  pair: ^0.1.2
  go_router: ^14.6.2
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  flutter_svg: ^2.0.16
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2
  share_plus: ^10.1.3
  intl: any
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.1
  android_intent_plus: ^5.2.1
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - path: assets/images/
    - path: assets/svg/
    
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100