import 'package:flutter/material.dart';

class MesColorSchemes {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff2e628c),
    surfaceTint: Color(0xff2e628c),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffcde5ff),
    onPrimaryContainer: Color(0xff0b4a72),
    secondary: Color(0xff51606f),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffd5e4f6),
    onSecondaryContainer: Color(0xff3a4857),
    tertiary: Color(0xff67587a),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffeedcff),
    onTertiaryContainer: Color(0xff4f4061),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff93000a),
    surface: Color(0xfff7f9ff),
    onSurface: Color(0xff181c20),
    onSurfaceVariant: Color(0xff42474e),
    outline: Color(0xff72777f),
    outlineVariant: Color(0xffc2c7cf),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2d3135),
    inversePrimary: Color(0xff9acbfa),
    primaryFixed: Color(0xffcde5ff),
    onPrimaryFixed: Color(0xff001d32),
    primaryFixedDim: Color(0xff9acbfa),
    onPrimaryFixedVariant: Color(0xff0b4a72),
    secondaryFixed: Color(0xffd5e4f6),
    onSecondaryFixed: Color(0xff0e1d2a),
    secondaryFixedDim: Color(0xffb9c8da),
    onSecondaryFixedVariant: Color(0xff3a4857),
    tertiaryFixed: Color(0xffeedcff),
    onTertiaryFixed: Color(0xff221533),
    tertiaryFixedDim: Color(0xffd2bfe7),
    onTertiaryFixedVariant: Color(0xff4f4061),
    surfaceDim: Color(0xffd8dadf),
    surfaceBright: Color(0xfff7f9ff),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff1f4f9),
    surfaceContainer: Color(0xffeceef3),
    surfaceContainerHigh: Color(0xffe6e8ee),
    surfaceContainerHighest: Color(0xffe0e2e8),
  );

  // // Light + High Contrast Scheme
  // ThemeData lightHighContrast() {
  //   return theme(
  //     const ColorScheme(
  //       brightness: Brightness.light,
  //       primary: Color(0xFF002344),
  //       onPrimary: Color(0xFFFFFFFF),
  //       primaryContainer: Color(0xFF1B4472),
  //       onPrimaryContainer: Color(0xFFFFFFFF),
  //       secondary: Color(0xFF182332),
  //       onSecondary: Color(0xFFFFFFFF),
  //       secondaryContainer: Color(0xFF394354),
  //       onSecondaryContainer: Color(0xFFFFFFFF),
  //       tertiary: Color(0xFF3B103A),
  //       onTertiary: Color(0xFFFFFFFF),
  //       tertiaryContainer: Color(0xFF61325D),
  //       onTertiaryContainer: Color(0xFFFFFFFF),
  //       error: Color(0xFF4E0002),
  //       onError: Color(0xFFFFFFFF),
  //       errorContainer: Color(0xFF8C0009),
  //       onErrorContainer: Color(0xFFFFFFFF),
  //       surface: Color(0xFFF8F9FF),
  //       onSurface: Color(0xFF191C20),
  //       surfaceTint: Color(0xFFDDE3EA),
  //       onSurfaceVariant: Color(0xFF1E2529),
  //       outline: Color(0xFF3D4449),
  //       outlineVariant: Color(0xFF3D4449),
  //       scrim: Color(0xFF000000),
  //       inverseSurface: Color(0xFF2F3036),
  //       onInverseSurface: Color(0xFFFFFFFF),
  //       inversePrimary: Color(0xFFE3ECFF),
  //       surfaceDim: Color(0xFFDAD9E0),
  //       surfaceBright: Color(0xFFFAF8FF),
  //       surfaceContainerLowest: Color(0xFFFFFFFF),
  //       surfaceContainerLow: Color(0xFFF4F3FA),
  //       surfaceContainer: Color(0xFFEEEDF4),
  //       surfaceContainerHigh: Color(0xFFE8E7EF),
  //       surfaceContainerHighest: Color(0xFFE2E2E9),
  //     ),
  //   );
  // }

  // Dark + Normal Contrast Scheme
  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xff9acbfa),
    surfaceTint: Color(0xff9acbfa),
    onPrimary: Color(0xff003352),
    primaryContainer: Color(0xff0b4a72),
    onPrimaryContainer: Color(0xffcde5ff),
    secondary: Color(0xffb9c8da),
    onSecondary: Color(0xff233240),
    secondaryContainer: Color(0xff3a4857),
    onSecondaryContainer: Color(0xffd5e4f6),
    tertiary: Color(0xffd2bfe7),
    onTertiary: Color(0xff382a49),
    tertiaryContainer: Color(0xff4f4061),
    onTertiaryContainer: Color(0xffeedcff),
    error: Color(0xffffb4ab),
    onError: Color(0xff690005),
    errorContainer: Color(0xff93000a),
    onErrorContainer: Color(0xffffdad6),
    surface: Color(0xff101418),
    onSurface: Color(0xffe0e2e8),
    onSurfaceVariant: Color(0xffc2c7cf),
    outline: Color(0xff8c9198),
    outlineVariant: Color(0xff42474e),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffe0e2e8),
    inversePrimary: Color(0xff2e628c),
    primaryFixed: Color(0xffcde5ff),
    onPrimaryFixed: Color(0xff001d32),
    primaryFixedDim: Color(0xff9acbfa),
    onPrimaryFixedVariant: Color(0xff0b4a72),
    secondaryFixed: Color(0xffd5e4f6),
    onSecondaryFixed: Color(0xff0e1d2a),
    secondaryFixedDim: Color(0xffb9c8da),
    onSecondaryFixedVariant: Color(0xff3a4857),
    tertiaryFixed: Color(0xffeedcff),
    onTertiaryFixed: Color(0xff221533),
    tertiaryFixedDim: Color(0xffd2bfe7),
    onTertiaryFixedVariant: Color(0xff4f4061),
    surfaceDim: Color(0xff101418),
    surfaceBright: Color(0xff36393e),
    surfaceContainerLowest: Color(0xff0b0f12),
    surfaceContainerLow: Color(0xff181c20),
    surfaceContainer: Color(0xff1c2024),
    surfaceContainerHigh: Color(0xff272a2f),
    surfaceContainerHighest: Color(0xff313539),
  );

  // // Dark + High Contrast Scheme
  // ThemeData darkHighContrast() {
  //   return theme(
  //     const ColorScheme(
  //       brightness: Brightness.dark,
  //       primary: Color(0xFFFBFAFF),
  //       onPrimary: Color(0xFF000000),
  //       primaryContainer: Color(0xFFABCDFF),
  //       onPrimaryContainer: Color(0xFF000000),
  //       secondary: Color(0xFFFBFAFF),
  //       onSecondary: Color(0xFF000000),
  //       secondaryContainer: Color(0xFFC0CBE0),
  //       onSecondaryContainer: Color(0xFF000000),
  //       tertiary: Color(0xFFFFF9FA),
  //       onTertiary: Color(0xFF000000),
  //       tertiaryContainer: Color(0xFFF5B7EB),
  //       onTertiaryContainer: Color(0xFF000000),
  //       error: Color(0xFFFFF9F9),
  //       onError: Color(0xFF000000),
  //       errorContainer: Color(0xFFFFBAB1),
  //       onErrorContainer: Color(0xFF000000),
  //       surface: Color(0xFF111318),
  //       onSurface: Color(0xFFE1E2E9),
  //       surfaceTint: Color(0xFF41484D),
  //       onSurfaceVariant: Color(0xFFF8FBFF),
  //       outline: Color(0xFFC5CCD2),
  //       outlineVariant: Color(0xFFC5CCD2),
  //       scrim: Color(0xFF000000),
  //       inverseSurface: Color(0xFFE2E2E9),
  //       onInverseSurface: Color(0xFF000000),
  //       inversePrimary: Color(0xFF002B52),
  //       surfaceDim: Color(0xFF121318),
  //       surfaceBright: Color(0xFF38393F),
  //       surfaceContainerLowest: Color(0xFF0D0E13),
  //       surfaceContainerLow: Color(0xFF1A1B21),
  //       surfaceContainer: Color(0xFF1E1F25),
  //       surfaceContainerHigh: Color(0xFF282A2F),
  //       surfaceContainerHighest: Color(0xFF33343A),
  //     ),
  //   );
  // }
}
